#!/bin/sh
# Script for opening up a Rails project. Opens up one window each aspect of
# MVC, and another two for shell and servers.

# change to URP folder (Zsh alias)
urp


# Start up an URP session
tmux start-server
tmux new-session -d -s URP -n Models
tmux new-window -tURP:2 -n Views
tmux new-window -tURP:3 -n Controllers
tmux new-window -tURP:4 -n Server
tmux new-window -tURP:5 -n Shell

tmux send-keys -tURP:1 'urp'
tmux send-keys -tURP:2 'urp'
tmux send-keys -tURP:3 'urp'
tmux send-keys -tURP:4 'urp && rails s'
splitw -h -p 50 'urp && rake sunspot:solr:run'
tmux send-keys -tURP:5 'urp'

tmux select-window -tURP:0
tmux attach-session -d -tURP
